spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 436010556731613
            client-secret: 2b2c3cbb69cfe7c8151aa06b501adb3c
            scope:
            - email
            - public_profile
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  application:
    name: Oauth2-Facebook-Login