spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 436010556731613
            client-secret: 
            scope:
              - email
              - public_profile
          
           
            
             