spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: <facebook client Id>
            client-secret: <facebook secret Id>
            scope:
            - email
            - public_profile
  mvc:
    view:
      prefix: WEB-INF/jsp/
      suffix: .jsp
  application:
    name: Oauth2-Facebook-Login